// <auto-generated />
using System;
using Gestion.Personne.Api.DContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gestion.Personne.Api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210309092714_Person")]
    partial class Person
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("Gestion.Personne.Api.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ListPersonnes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0889ae07-af92-4969-a0de-60d55f690298"),
                            Nom = "Liuzzo",
                            Prenom = "Giosue"
                        },
                        new
                        {
                            Id = new Guid("75e655e3-dfc6-4c4d-920f-0ee31d11b2bd"),
                            Nom = "Natale",
                            Prenom = "Elisa"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
