// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model.Global;

namespace Model.Global.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210310084441_Person")]
    partial class Person
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12");

            modelBuilder.Entity("Model.Global.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ListPersons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b384a697-00e0-4cb1-9d5f-0f75e85a323a"),
                            Nom = "Liuzzo",
                            Prenom = "Giosue"
                        },
                        new
                        {
                            Id = new Guid("bc839b51-4121-445d-9b24-2c2328445807"),
                            Nom = "Natale",
                            Prenom = "Elisa"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
